### ISSUE TITLE
htmdmol.tools.voxeldescriptors.viewVoxelFeatures does not show anything with a ligand

### ISSUE THREAD

**Issue by hawk31** [compsciencelab/htmdmol#6]
```python
import os

import numpy as np
from rdkit.Chem import SDMolSupplier

from htmdmol.smallmol.smallmollib import SmallMol
from htmdmol.molecule import Molecule
from htmdmol.tools.voxeldescriptors import viewVoxelFeatures, getVoxelDescriptors

boxsize = [24]*3

center = np.load('center.npy')
sp = next(SDMolSupplier('ligand.sdf'))
sm = SmallMol(sp)

features_ligand, centers_ligand, nvoxels_ligand = getVoxelDescriptors(sm, center=center, boxsize=boxsize)
viewVoxelFeatures(features_ligand, centers_ligand, boxsize)
```

outputs nothing:

![image](https://user-images.githubusercontent.com/6875576/53738754-598aeb80-3e90-11e9-8237-50d37470517f.png)

[4ykt.zip](https://github.com/compsciencelab/htmdmol/files/2926666/4ykt.zip)

**Comment by stefdoerr** [comment]
are you sure the center is correctly positioned? Did you look if the isovalues are movable in the representations?

**Comment by hawk31** [comment]
The gaussian cube object does not even show in VMD. Look at the main window I shared.

**Comment by stefdoerr** [comment]
https://github.com/compsciencelab/htmdmol/commit/217f2f79b5906396580a0656b6a94b6c3603f5a8

Fixed. Stupid mistake of mine
