### ISSUE TITLE
de-hardcode draw argument for viewVoxelFeatures

### ISSUE THREAD

**Issue by SNWBRS** [compsciencelab/htmdmol#7]
hardcoded draw='wireframe' looks trippy

**Comment by stefdoerr** [comment]
It's quite useful if you overlay it over a molecule though. But ok I will make it an option :)

**Comment by stefdoerr** [comment]
https://github.com/compsciencelab/htmdmol/commit/124c9743112dd958244af0bdc53dc1b1d268e4f3
fixed
